import type { Metadata } from "next";
import "./globals.css";
import {Syne_Mono } from "next/font/google";
const font = Syne_Mono({ subsets: ["latin"], weight: '400' })

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "SAPi",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`} >
        <Header/>
        {children}
      </body>
    </html>
  );
}
