import type { Metadata } from "next";
import "./globals.css";
import { Montserrat_Alternates } from "next/font/google";
const font = Montserrat_Alternates({ subsets: ["latin"], weight: '400' })
import Header from "@/components/Header";
import { ThemeProvider } from 'next-themes'
import { AptosWalletProvider } from "@/context/AptosWalletProvider";
import NextTopLoader from 'nextjs-toploader';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: "SAPi",
  description: "Generated by create next app",
};
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`} >
        <ThemeProvider>
          <NextTopLoader
            color="#FEBF32"
            height={2}
            speed={500}
            showSpinner={false}
          />
          <AptosWalletProvider>
            <Header />
            {children}
            <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
          </AptosWalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
