import type { Metadata } from "next";
import "./globals.css";
import { Montserrat_Alternates } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import { AptosWalletProvider } from "@/context/AptosWalletProvider";
import { ToastContainer } from 'react-toastify';
import NextTopLoader from 'nextjs-toploader';
import Header from "@/components/Header";
import SiteLoader  from '@/components/ui/SiteLoader'

const font = Montserrat_Alternates({ subsets: ["latin"], weight: '400' })
export const metadata: Metadata = {
  title: "SAPi",
  description: "Generated by create next app",
};
const def_theme = process.env.NEXT_PUBLIC_CURRENT_THEME || 'light';
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`} >
        <ThemeProvider attribute="data-theme" defaultTheme={def_theme}>
          <NextTopLoader color="#9EC8B9" height={2} speed={500} showSpinner={false} />
          <SiteLoader />
          <AptosWalletProvider>
            <Header />
            {children}
            <ToastContainer position="bottom-right" autoClose={3000} hideProgressBar newestOnTop pauseOnFocusLoss draggable={false} pauseOnHover limit={5} stacked theme="dark" />
          </AptosWalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
